### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Xvezda** [Xvezda/dotfiles#5]
- [x] Fix tmux scheme version >= 2.3 syntax
- [x] zshrc, zprofile cross platform
- [ ] Check modified script also works on Msys2

**Comment by Xvezda** [comment]
Dotfiles가 Mac OS X 환경에 너무 의존적임

**Comment by Xvezda** [comment]
무리하게 진행하다 꼬일 가능성이 있기 떄문에, 우선 각각의 branch로 나누었다가 이후에 merge 하는것으로

**Comment by Xvezda** [comment]
dcafac7ecf9798431c0d80469f24294957e3f1ed

**Comment by Xvezda** [comment]
Dup #4
